# File: docker-compose.yml
version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - gateway_network

  # Backend 1
  backend_alpha:
    image: jmalloc/echo-server
    environment:
      - PORT=8080
    networks:
      - gateway_network

  # Backend 2
  backend_beta:
    image: jmalloc/echo-server
    environment:
      - PORT=8080
    networks:
      - gateway_network

  # Our API Gateway
  gateway:
    build: .
    ports:
      - "8080:8080"
    environment:
      - REDIS_ADDR=redis:6379
    depends_on:
      - redis
      - backend_alpha
      - backend_beta
    networks:
      - gateway_network

networks:
  gateway_network:
    driver: bridge