version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - gateway_network

  backend_service:
    image: jmalloc/echo-server
    ports:
      - "9000:8080"
    networks:
      - gateway_network

  # 3. Gateway Node 1
  gateway_alpha:
    build: .
    ports:
      - "8080:8080"
    environment:
      - REDIS_ADDR=redis:6379
      - BACKEND_URL=http://backend_service:8080
    depends_on:
      - redis
      - backend_service
    networks:
      - gateway_network

  # 4. Gateway Node 2 
  gateway_beta:
    build: .
    ports:
      - "8081:8080"
    environment:
      - REDIS_ADDR=redis:6379
      - BACKEND_URL=http://backend_service:8080
    depends_on:
      - redis
      - backend_service
    networks:
      - gateway_network

networks:
  gateway_network:
    driver: bridge